In [1]:
# if we pass any data type likr list, tuple it will get converted into ndarray
#passing list into array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# if we pass any data type likr list, tuple it will get converted into ndarray
# passing tuple into array
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# accessing array elements

In [3]:
# accessing 1D array
# array index start from 0
arr=np.array([1,2,3,4,5])
print(arr[3])

4


In [4]:
#accessing 2D array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("2nd row and 3rd elwment:",arr[1,2])

2nd row and 3rd elwment: 7


In [5]:
#accessing 3D array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("choosing 7 :",arr[1,0,0])

choosing 7 : 7


In [6]:
# negative indexing
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("2nd last element from 2nd row:",arr[1, -2])

2nd last element from 2nd row: 7


# slicing of array
#slicing order [start:end:step]
#(start<end)

In [7]:
# slicing 1D array
arr=np.array([1,2,3,4,5])
print(arr[0:4])

[1 2 3 4]


In [8]:
# if you want to slice till end live blank afer colon(:)
arr[2:]

array([3, 4, 5])

In [9]:
# if you want to slice from starting live starting blank
arr[:4]

array([1, 2, 3, 4])

In [10]:
# negative slicing
arr[-3:-1]

array([3, 4])

In [11]:
arr[-1:-3]  # This returns an empty array since the slice starts at index -1 and ends at index -3 (exclusive),
            # but slices must move in a positive direction by default (start < end)

array([], dtype=int64)

In [12]:
# stepping through array
arr[0:len(arr):2]
# or arr[::2]

array([1, 3, 5])

In [13]:
print(len(arr))

5


# array data types

In [14]:
# python compiler initially self uderstand the data type of the elements.
li=[1,2,3,4,5,6]
arr=np.array(li)
print(arr)
print(arr.dtype)

[1 2 3 4 5 6]
int64


In [15]:
# we can change the data type of the elements by using dtype="".
# here we changed the data type from int64 to string.
arr=np.array(li,dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [16]:
# here we changed the data type from int64 to float.
arr=np.array(li,dtype="f")
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5. 6.]
float32


In [17]:
# in case if we try to convert string to intiger we will get an error
arr=np.array(['a',1,2,3],dtype="i")
print(arr)
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
# best way to convert array is create copy of existing array using astype() function.
arr=np.array([1,4,2,5,3])
new_arr=arr.astype('f')
print(arr)
print(arr.dtype)
print("new array convertes to float",new_arr)
print("new arrays  data type",new_arr.dtype)

# Difference between copy() and view()
## copy():
copy is a new array.<br>
changes made in copy does not affect array.<br>
changes made in array does not affect copy.<br>
## view():
view does not own the data.<br>
any changes made in array affect the view<br>
changea made in view affect array.<br>

In [ ]:
# let's create an array
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)

In [ ]:
# we see the copy()
x = arr.copy()
arr[0]=99
print(arr)
print(x)
# we can see in the result the copy does not get affected by change in original

In [18]:
# we see the view()
y = arr.view()
arr[0]=99
print(arr)
print(y)
# we can see in the result the both get affeccted by view()

[99.  2.  3.  4.  5.  6.]
[99.  2.  3.  4.  5.  6.]


## check the origanal data by base
if we get none then array own its data.<br>
other wise base attrribute reffers original data.<br>
we can use it to find original data if we make a lot of changes.<br>

In [19]:
# original data
print(arr.base)
# x is an array with copy
print(x.base)
# y is an array with view
print(y.base)

None


NameError: name 'x' is not defined

# shape of an array and reahapig of array
it returns the tuple having number of elements in each dimention<br>

In [20]:
# creating 3 lists
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=[11,12,13,14,15]
# creating an array
arr=np.array([[l1,l2,l3]])
print(arr)
print(arr.shape)
# output means that 1st dimension have one element, 2nd dimension have three elements, 3rd dimension have 5 elements each.

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
(1, 3, 5)


In [21]:
# reahaping this array into 1 dimesions
new_arr=arr.reshape(1,15)
print(new_arr)
print(new_arr.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
(1, 15)


In [22]:
# if we check the change dimension have original elements or not
print(new_arr.base)
#we get the original array it is view()

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


## unknown dimension and flatter the array
if we don't know the dimension use the reshape(dim,dim,-1)<br>
using reshape(-1) we can convert array to 1 dimensional<br>

In [23]:
# flattering the array
print(arr.reshape(-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [24]:
# if we dont know dimension but know about arrangment
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
new_arr=arr.reshape(2,4,-1)
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


# iterating through array
## iterating through 1D,2D,3D array
we iterate through array using for loop.<br>
we have to use for loop according to dimensions to iterate through  all elements.

## iterating through 1D array

In [25]:
# iterate through 1D array
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)
print("iterating through each element of 1D array")

1
2
3
4
5
6
iterating through each element of 1D array


In [26]:
# we have to notice a difference if we use print with tab
# here the print is considered in for loop
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)
    print("iterating through each element of 1D array")

1
iterating through each element of 1D array
2
iterating through each element of 1D array
3
iterating through each element of 1D array
4
iterating through each element of 1D array
5
iterating through each element of 1D array
6
iterating through each element of 1D array


## iterating through 2D array

In [27]:
# ierating through a 2D array
# iterating through 1st dimension
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print("iteating towards 1st dimension elements")
    print(x)

iteating towards 1st dimension elements
[1 2 3]
iteating towards 1st dimension elements
[4 5 6]


In [28]:
#iterating through the 2nd dimension so we get the actual elements
print("dimension of array:",arr.ndim)
print("origanility of elements:",arr.base)
for x in arr:
    for y in x:
        print(y)
print("hrer we get the actual elements.")

dimension of array: 2
origanility of elements: None
1
2
3
4
5
6
hrer we get the actual elements.


## iterating through 3D array

In [29]:
# creating 1D array with 18 elements
arr=np.array([1,2,3,4,5,6,7,8,9,11,22,33,44,55,66,77,88,99])
# reshaping array into 3 dimensions
narr=arr.reshape(2,3,3)
print(narr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]


In [30]:
# iterating through 1st dimensiion
for x in narr:
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [31]:
# iterating through 2nd dimension
for x in narr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[11 22 33]
[44 55 66]
[77 88 99]


In [32]:
# iterating through 3rd dimension 
# here we get actual elements
for x in narr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
11
22
33
44
55
66
77
88
99


## use of nditer()
we can iterate through  each element<br>
we can iterate with stepping size<br>
we can iterate with different data types

In [33]:
# iterating theough each element 
# we can also use flatter(reshape(-1))
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
for x in np.nditer(arr):
    print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


In [34]:
# iterating with stapping
# iterrating through first row
print("iterating with stepping:")
for y in np.nditer(arr[:,:,::2]):
    print(y)

iterating with stepping:
1
3
4
6
7
9
10
12


In [35]:
# itreating selecting datatype
print("itereating with stepping:")
for z in np.nditer(arr, flags=["buffered"], op_dtypes=["S"]):
    print(z)

itereating with stepping:
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')


## enumerate
it will give indexing of array elements

In [36]:
# we will iterate through 3D array
for idx,x in np.ndenumerate(arr):
    print("iterating through position",idx)
    print(idx,x)

# giving space by \n
print("\n")

# we will flatter array and then iterate through each element
new_arr=arr.reshape(-1)
print("iterating through 1D array:")
for idx,y in np.ndenumerate(new_arr):
    print(idx,y)

iterating through position (0, 0, 0)
(0, 0, 0) 1
iterating through position (0, 0, 1)
(0, 0, 1) 2
iterating through position (0, 0, 2)
(0, 0, 2) 3
iterating through position (0, 1, 0)
(0, 1, 0) 4
iterating through position (0, 1, 1)
(0, 1, 1) 5
iterating through position (0, 1, 2)
(0, 1, 2) 6
iterating through position (1, 0, 0)
(1, 0, 0) 7
iterating through position (1, 0, 1)
(1, 0, 1) 8
iterating through position (1, 0, 2)
(1, 0, 2) 9
iterating through position (1, 1, 0)
(1, 1, 0) 10
iterating through position (1, 1, 1)
(1, 1, 1) 11
iterating through position (1, 1, 2)
(1, 1, 2) 12


iterating through 1D array:
(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


# joining of array
- we join array by axse<br>
- joining means putting data of two or more array in one array

## joining by concatenate()
- join array along existating axis
- array must have same shape expect array going to concatenate
- axis=1 means by row<br>
- axis=0 means by column<br>

## joining array by stack function
- stack function generates a new axis
- both array must have sameshape
- if you are using only  stack then use axis=1(row) or 0(column)<br>
- there is another option use:<br>
  hstack to go along row<br>
  vstack to go along column<br>
  dstack to go along height<br>

In [37]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
arr1=np.array(l1)
arr2=np.array(l2)
arr_c=np.concatenate((arr1,arr2))
arr_s=np.stack((arr1,arr2))
print("array with concatnation:")
print(arr_c)
print(arr_c.shape)
print("array with stack:")
print(arr_s)
print(arr_s.shape)

array with concatnation:
[ 1  2  3  4  5  6  7  8  9 10]
(10,)
array with stack:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [38]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
# we give here axis=1 so compiler first go through row 1 and then by row 2
print(arr)
print(arr.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [40]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr_1=np.stack((arr1,arr2),axis=1)
print("array going through columns:")
print(arr1.shape)
print(arr_1)

array going through columns:
(4,)
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [41]:
# using hstack to go along row
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [45]:
# using vstack to go along column
arr=np.vstack((arr1,arr2))
print("originality of array:",arr.base)
print("size of array",arr.shape)
print(arr)

originality of array: None
size of array (2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [46]:
# using dstack to go along depth
arr=np.dstack((arr1,arr2))
print("originality of array:",arr.base)
print("size of array",arr.shape)
print(arr)

originality of array: None
size of array (1, 4, 2)
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# splitting of an array
- we can break one array into multiple<br>
- use array_split() function<br>

In [48]:
# breaking of array into muliple arrays
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [50]:
# we can take split array as new elements
print("0th position element of array:",newarr[0])
print("1st position element of array:",newarr[1])
print("2nd position element of array:",newarr[2])

0th position element of array: [1 2 3]
1st position element of array: [4 5 6]
2nd position element of array: [7 8 9]


In [52]:
# splitting of a 2D array
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


use hsplit() method to split along vertical

In [53]:
newarr=np.hsplit(arr,3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# searching into an array 
## using the where() method
- it will give the position of particular element

In [55]:
# we are using where method to find element position
arr=np.array([23,53,6,34,76,6,35,6])
x=np.where(arr==6)
print("positions of element 6 is ",x)

position of element 6 is  (array([2, 5, 7]),)


In [56]:
# we are going to search position of even numbers
x=np.where(arr%2==0)
print("positions of even numbers are:",x)

positions of even numbers are: (array([2, 3, 4, 5, 7]),)


## using the search sorted() function
- it gives a position where the particular number can be insertes to maintain the order.
- we can use side="right" to find particular position from right side
- it is assusmed to be we use the searchsorted() function on sorted array

In [61]:
arr=np.array([11,15,18,19,22,45])
x=np.searchsorted(arr,20)
y=np.searchsorted(arr,[2,7,16,38,50])
print("searching position for single element:",x)
print("searching position for mutiple elements:",y)

searching position for single element: 4
searching position for mutiple elements: [0 0 2 5 6]


# sorting of array
- arranging array in an inceasing order.
- we use np.sort(name_of_array) function.

In [62]:
# example for integer array
arr=np.array([11,43,56,23,7,2,0,45,76])
print(np.sort(arr))

[ 0  2  7 11 23 43 45 56 76]


In [64]:
# example for character array
arr=np.array(['a','f','r','w','f','kri','app','rs'])
print(np.sort(arr))

['a' 'app' 'f' 'f' 'kri' 'r' 'rs' 'w']


In [67]:
# sorting a 2D array
arr=np.array([[2,6,33,3,1],[34,56,34,23,23]])
print(np.sort(arr))

[[ 1  2  3  6 33]
 [23 23 34 34 56]]


# filtering of array
- a boolian list along index/position is created.
- if the index have true then that element is considered.
- if the index have flase then the element is not considered.

In [71]:
# we are going to filter all even numbers from array
# lets create an array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
# create an empty list to store the booline values
bool_list=[]
# creating a for loop to iterate through array elements
for el in arr:
    if el%2==0:
        bool_list.append(True)
    else:
        bool_list.append(False)
# creating an array for even numbers using bool_list
newarr=arr[bool_list]
print("initial array:",arr)
print("boolian list after filtering:",bool_list)
print("fineal array of even numbers:",newarr)

initial array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
boolian list after filtering: [False, True, False, True, False, True, False, True, False, True, False, True, False, True, False]
fineal array of even numbers: [ 2  4  6  8 10 12 14]
